export const items = [
  {
    name: 'Paris',
    ind: 0,
    imgSrc:
      'https://images.unsplash.com/photo-1471623320832-752e8bbf8413?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1549&q=80',
    ipsumPool: [
      `Located in the center of Old Paris, Notre Dame is something you have to see when you are in Paris. `,
      `The famous left bank of the Seine is lined with booksellers that have plied their trade since the early 1900's. `,
      `This is the district of the Kings of France, with the Royal Palace, Tuileries Gardens, the Louvre or La Cité Palace, and the Seine River, best enjoyed from the water on a Seine River cruise. `,
      `On the other hand, Paris 1 is also the district of Les Halles. `,
      `The most beautiful sights to visit in Paris 2 are the Covered Passages. `,
      `Le Marais has also had its fair share of famous residents, including Victor Hugo, John Galliano and Jim Morrison. `,
      `The Ile de la Cite was the birthplace of Paris over 2000 years ago and here you will find the Notre Dame Cathedral. `,
      `The Latin quarter is known as the student district. `,
      `You will also find the Pantheon, Odeon and the Jardin du Luxembourg. `,
      `Closer to the Seine near St Michel, you will find many takeaway shops and souvenir shops. `,
      `This is where people go to see and be seen, and has been the haunt of many famous people over the years: Ernest Hemingway, Brigitte Bardot, Sharon Stone, Robert de Niro, Yves Saint Laurent. `,
      `The wealthy 7th quarter is home to foreign embassies and important international visitors. `,
      `Traditionally, France nobility lived in this quarter, and it is sometimes referred to as the Faubourg neighborhood. `,
      `One of the most famous roads in the world, the Champs-Elysees is the finishing point of the Tour de France held annually in July. `,
      `Other sights worth seeing are the Arc de Triomphe, Place de la Concorde and the Elysees Palace, which is the French President’s home. `,
      `The Oberkampf area is popular for its nightlife. `,
      `Bercy is a large residential neighbourhood, best known for the Bois de Vincennes, the largest public park in Paris. `,
      `Go to the Place de Trocadero for excellent views of the Eiffel Tower. `,
      `The area near the Arc de Triomphe and Parc Monceau is very upmarket, while the Batignolles neighborhood is more bohemian. `,
      `Home of Parc de Butte Chaumont, one of the largest parks in Paris complete with a temple and an artificial lake. `,
      `The most well-known attraction in this quarter is the cemetery Pere Lachaise, resting place of many famous people including Oscar Wilde, Edith Piaf and Jim Morrison. `,
    ],
  },
  {
    name: 'Rome',
    ind: 1,
    imgSrc:
      'https://images.unsplash.com/photo-1517993873665-f7a8c5021470?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1575&q=80',
    ipsumPool: [
      `Rome is teeming with history and life. `,
      `Rome can be overwhelming. `,
      `The Colosseum is the largest amphitheater ever built! `,
      `Also visit the Arch of Constantine, located next to the Colosseum. `,
      `The first settlement of Rome started with Palatine Hill. `,
      `In front of Piazza Venezia is a gigantic pure-white marble moment that has a panoramic view of the entire city. `,
      `Outside the Pantheon, at Piazza Della Rotonda there are loads of terraces to have a break and get a delicious Italian espresso. `,
      `Every day, over 3000 EUR is collected from the fountain and donated to a non-profit that provides food for the homeless in Rome. `,
      `Rise and shine early and be the first at Vatican City. `,
      `Visit the St. Peter’s Square & Basilica, the Vatican Museums, and the Sistine Chapel. `,
      `St. Peter’s Square is the large plaza in front of the basilica where people gather on Sundays when the Pope does a short greeting from his window. `,
      `These neighborhoods may be considered Baroque Rome. `,
      `Ancient Rome was built on seven hills surrounded by the 4th century BC Servian Wall. `,
      `The Vatican Hill, Janiculum Hill, and Pincian Hill where you’ll find the Via Veneto and Borghese neighborhoods, were not part of the original seven hills. `,
      `The most popular area of Rome to explore is the historic center – Rome’s centro storico. `,
      `The beauty of Rome’s centro storico combined with its historical significance makes it the most spectacular city in the world for tourists. `,
      `The big stone gate known as the Porta del Popolo was originally the Porta Flaminia, which was the starting point for the Via Flaminia, the ancient Roman road to the north. `,
      `The main points of interest in the square are the Egyptian obelisk in the middle, steps up to the Pincio, and two churches in the square, church of Santa Maria in Montesanto and Santa Maria dei Miracoli. `,
      `The Capitoline Museums are a group of art and archeological museums in Piazza del Campidoglio, on top of the Capitoline Hill. `,
    ],
  },
  {
    name: 'Barcelona',
    ind: 2,
    imgSrc:
      'https://images.unsplash.com/photo-1533675427724-01a3a2b507d6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80',
    ipsumPool: [
      `Barcelona is the perfect getaway in Europe. `,
      `Continue to Palau de la Música Catalana, this is about a 10-minute walk through the popular neighborhood called El Born. `,
      `A district inside the historic center of Barcelona, with small streets, art galleries and boutique shops. `,
      `From Palau de la Música make your way to the Cathedral of Barcelona. `,
      `It owns loads of little bars, restaurants, and shops. `,
      `Start the day at Parc Guell who maybe be called the most creative park in the world. `,
      `This will take to the top of Montjuic, which is a hill in Barcelona overlooking the Barcelona harbor. `,
      `Besides the garden check out the Montjuic Castle! `,
      `This city offers some beautiful places to stay. `,
      `Barcelona is one of the easiest cities to get around. `,
      `You can buy a 10-trips ticket at one of the subway stations. `,
      `There’s no attraction more synonymous with Barcelona than the illustrious Sagrada Familia, a Gaudi creation that has been in the works for almost 140 years. `,
      `From impressive art museums like the Museu Nacional d’Art de Catalunya, Museu Picasso and the Fundació Joan Miró to choices that are a bit more offbeat like museums featuring funeral carriages, chocolate and marijuana, you definitely need to stop by at least one Barcelona museum to make the most of your visit. `,
    ],
  },
  {
    name: 'San Francisco',
    ind: 3,
    imgSrc:
      'https://images.unsplash.com/photo-1547191185-52e112942fb1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80',
    ipsumPool: [
      `English is the main language spoken in San Francisco, but significant Chinese and Mexican populations mean that Chinese and Spanish are also spoken by many. `,
      `Some of the loveliest residential areas are located here, as well as some former military posts – Fort Mason and the Presidio. `,
      ` Visit “The Marina” for some fancier bars and restaurants. `,
      `North Beach is also home to the Italian district. `,
      `The Mission is the best district to soak up some local flavor. `,
      `There is some good hiking around Lake Merced and the San Francisco Zoo is also a great place to visit for families. `,
      `Combining the elegance and gentility of an Edwardian home, the Union Street Inn is the perfect pied-à-terre for those who want to explore San Francisco. `,
      `San Francisco’s most historic hotel, Palace Hotel, dates back to 1875 and is located in Downtown SF. `,
      `Also known as the Lillian Coit Memorial Tower, this pretty place in Telegraph Hill tells the tale of a socialite turned rouge firefighter. `,
      `On the southwest side of the Golden Gate Bridge, you’ll find a jaw-dropping view. `,
      `Talking of Lombard Street, if you’re in the Russian Hill neighbourhood it’s definitely worth checking out what’s known as one of America’s crookedest streets. `,
      ` Looking down Lombard Street you can see The Coit Tower in the distance. `,
      `San Francisco is a must when you’re visiting California. `,
      `Make your way to Downtown through the Dragon Gate, and continue on to Union Square. `,
      `Find your way to the Castro, San Francisco’s historically LGBT neighborhood, where good food awaits in the form of La Mediterranee for Mediterranean comfort food or Sushi Time, a tiny subterranean sushi bar that serves some of the city’s freshest sushi. `,
    ],
  },
  {
    name: 'New York',
    ind: 4,
    imgSrc:
      'https://images.unsplash.com/photo-1549654747-1fe362f45d7b?ixlib=rb-1.2.1&auto=format&fit=crop&w=2134&q=80',
    ipsumPool: [
      `The Empire State Building is just not worth it in comparison to the view from the Top of the Rock! `,
      `It’s free & has a killer view of the Statue of Liberty from it. `,
      `The primary reason to visit Little Italy is the food. `,
      `This is also a pretty big residential area. `,
      `Apart from dozens of authentic Italian restaurants and bakeries, there are a few shops and cafes. `,
      `The Upper East Side is a tale of two cities. `,
      `Home to Columbia University, Lincoln Center, the American Museum of Natural History and the New York Historical Society, the Upper West Side is where the city’s theatrical and intellectual elites raise their families. `,
      `The residential neighborhood’s quiet, tree-lined streets and proximity to Central Park make it one of the most expensive places to live in New York. `,
      `Between its soul food restaurants, intimate jazz clubs and lively streetscapes, Harlem hits all five of your senses. `,
      `It might feel like a trek getting to the northern reaches of Manhattan, but it’s worth the journey. `,
      `When you hear the name Hell’s Kitchen, you instantly wonder what kind of trouble this neighborhood might be cooking up. `,
      `Those skyscrapers and traffic jams you picture when you think of New York become reality in Midtown. `,
      `If you like architecture, you’re in for a treat in Midtown East. `,
      `New York is a mecca for all things street art – the scene is constantly changing, evolving, and keeps getting better and more interesting, even for the non-initiated. `,
      `The West Village is full of great, quirky street art. `,
    ],
  },
];
